# Generated by Django 4.0.1 on 2022-01-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0003_infoline_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoline',
            name='importance',
            field=models.CharField(choices=[('EM', 'Emergency'), ('CO', 'Concern'), ('CR', 'Crucial'), ('PL', 'plain'), ('ME', 'Meaningless')], default='PL', max_length=2),
        ),
    ]
